### ISSUE TITLE
Deprecate EnumInterface::getName

### ISSUE THREAD

**Issue by yann-eugone** [yann-eugone/enum-bundle#15]
An enum already has an identifier : it's class.

Symfony did the same with form types in [2.8](https://github.com/symfony/symfony-docs/issues/5588).

[EnumInterface::getName](https://github.com/yokai-php/enum-bundle/blob/master/Enum/EnumInterface.php#L18) should be deprecated.

- [ ] Deprecate the method
- [ ] Update the doc
- [ ] Add a note for next major

**Comment by yann-eugone** [comment]
@J-Ben87 what do you think ?

**Comment by J-Ben87** [comment]
I totally agree, I have already been emulating this behaviour for a while:
```
public function getName()
{
    return static::class;
}
```

**Comment by yann-eugone** [comment]
The more I think about it, the more I wonder if this is a good idea.

I never tried something like this, but I wonder if this can be even better than what we do already :

```php
<?php

use Yokai\EnumBundle\Enum\EnumInterface;

class ConfigurableEnum implements EnumInterface
{
    private $name;
    private $choices;

    public function __construct($name, array $choices)
    {
        $this->name = $name;
        $this->choices = $choices;
    }

    public function getName()
    {
        return $this->name;
    }

    public function getChoices()
    {
        return $this->choices;
    }
}
```

```php
<?php

use Symfony\Component\Translation\TranslatorInterface;
use Yokai\EnumBundle\Enum\AbstractTranslatedEnum;

class ConfigurableTranslatedEnum extends AbstractTranslatedEnum
{
    private $name;
    private $values;

    public function __construct(TranslatorInterface $translator, $transPattern, $name, array $values)
    {
        parent::__construct($translator, $transPattern);

        $this->name = $name;
        $this->values = $values;
    }

    public function getName()
    {
        return $this->name;
    }

    public function getValues()
    {
        return $this->values;
    }
}
```

```yaml
services:
    enum.gender:
        class: ConfigurableEnum
        arguments:
            $name: 'member.gender'
            $choices:
                !php/const:AppBundle\Entity\Member::GENDER_MALE: 'Male'
                !php/const:AppBundle\Entity\Member::GENDER_FEMALE: 'Female'
    enum.state:
        class: ConfigurableTranslatedEnum
        arguments:
            $translator: '@translator'
            $transPattern: 'choice.member.state.%s'
            $name: 'member.state'
            $values:
                !php/const:AppBundle\Entity\Member::STATE_NEW
                !php/const:AppBundle\Entity\Member::STATE_VALIDATED
                !php/const:AppBundle\Entity\Member::STATE_DISABLED
```

- Keep constants in domain
- Not needed to create a new class for each enum

This require that Enum::getName exists...
